name: Build and Run C Program

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt update && sudo apt install -y gcc

    - name: Compile C program
      run: gcc your_program.c -o your_program

    - name: Run C program
      run: ./your_program

